server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    min-response-size: 1
  contextPath: /base-admin-mybatis/
  #解决spring-boot修改jsp文件重启才生效的问题，正式环境更改为false
  jsp-servlet:
    init-parameters:
      development: true
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #convertToNull解决日期为0报错问题
    url: jdbc:mysql://localhost:3306/base-admin?characterEncoding:utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    #解决mysql8小时不操作超时问题
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    max-idle: 10
    max-active: 100
    initialize: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    date-format: yyyy-MM-dd

#logging
logging:
  path:
  level:
    org:
      springframework:
        web: WARN
    com:
      supershen:
        example:
          dao: DEBUG

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.supershen.example.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

  
